### ISSUE TITLE
Hello there，I don't know why i couldn't download the pre-train model  

### ISSUE THREAD

**Issue by JJumperer** [alexanderkroner/saliency#23]
(finalwork) C:\Users\86185\Desktop\saliency-master>python main.py test -d cat2000 -p C:\Users\86185\Desktop\saliency-master\tset
>> Downloading pre-trained weights...Traceback (most recent call last):
  File "main.py", line 249, in <module>
    main()
  File "main.py", line 245, in main
    test_model(args.data, paths, config.PARAMS["device"])
  File "main.py", line 174, in test_model
    model_name[:-3])
  File "C:\Users\86185\Desktop\saliency-master\download.py", line 469, in download_pretrained_weights
    with zipfile.ZipFile(data_path + "tmp.zip", "r") as zip_ref:
  File "C:\Users\86185\anaconda3\envs\finalwork\lib\zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "C:\Users\86185\anaconda3\envs\finalwork\lib\zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

did i set the wrong environment or miss some steps?

**Comment by JJumperer** [comment]
by the way,i think you should add the requirement that the package's version of  numpy,  cause i could not run the code with a later version until i change it into 1.16.0

**Comment by JJumperer** [comment]
by the way,i suggest that you should add the requirement that the package's version of numpy, cause i could not run the code with a later version until i change it into 1.16.0

**Comment by JJumperer** [comment]
thanks,i checked again and found that i forgot to change the device into cpu
thanks for your wonderful code and your help
