### ISSUE TITLE
"Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses." 

### ISSUE THREAD

**Issue by jjbes** [alexanderkroner/saliency#27]
Hi Alexander,
I'm trying to use your pre-trained weights using `python ./saliency/main.py test -d mit1003 -p` on google colab. This code worked last week but is now displaying the following error :

```
>> Downloading pre-trained weights...Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1P_tWxBl3igZlzcHGp5H3T3kzsOskWeG6&export=download 

Traceback (most recent call last):
  File "./saliency/main.py", line 249, in <module>
    main()
  File "./saliency/main.py", line 245, in main
    test_model(args.data, paths, config.PARAMS["device"])
  File "./saliency/main.py", line 174, in test_model
    model_name[:-3])
  File "/content/saliency/download.py", line 469, in download_pretrained_weights
    with zipfile.ZipFile(data_path + "tmp.zip", "r") as zip_ref:
  File "/usr/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/content/saliency/weights/tmp.zip'```

**Comment by alexanderkroner** [comment]
Hi, apologies for the late reply! It seems that an outdated gdown version causes this error. I tested the code after updating gdown to version `4.6.3` and that fixes the issue!
